#!/bin/bash
### BEGIN INIT INFO
# Provides:             nodeApp
# Required-Start:       $local_fs
# X-UnitedLinux-Should-Start:
# Required-Stop:        $local_fs
# X-UnitedLinux-Should-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    node application
# Description:          node application 
### END INIT INFO

case "$1" in
        start)
                su - pi -c "forever start --spinSleepTime 5000 --sourceDir=/opt/app index.js"
                ;;
        stop)
                su - pi -c "forever stopall"
                forever stopall
                ;;
        restart)
                su - pi -c "forever restartall"
                forever restartall
                ;;
        status)
                su - pi -c "forever list"
                forever list
                ;;
esac

